name: Dependent jobs

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.FirstName }}
    steps:
      - uses: actions/checkout@v2
      - name: job2
        id: step1
        run: echo "FirstName=Abdullah" >> $GITHUB_OUTPUT
  job2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: job2
        run: echo ${{ needs.job1.outputs.output1}}
