name: jobs names

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: jobs-names
        env:
          job1_name: ${{ github.job }}
        run: |
          echo "job1 name is: $job1_name"
  job2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: jobs-names
        env:
          job2_name: ${{ github.job }}
        run: |
          echo "job2 name is: $job2_name"
